name: Deploy Javadoc

on:
  release:
    types: [ created ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
          server-id: xenondevs-nms
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build with Maven
        run: mvn -B clean install -P xenondevs-nms
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Create Javadoc
        run: mvn -B javadoc:javadoc -pl invui-core -P xenondevs-nms
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          folder: invui-core/target/site/apidocs/
